// eslint-disable-next-line import/no-anonymous-default-export
export default [
    {
        id: 1,
        title: "Thai Mango Chicken",
        price: 7.99,
        coverImg: "MangoChicken.jpg",
        thumbUp: "thumbUp.png",
        chilly:"",
        white:"white.png",
        openSpots: 100,
    },
    {
        id: 2,
        title: "General Thai Chicken",
        price: 7.99,
        coverImg: "GeneralChicken.webp",
        thumbUp: "thumbUp.png",
        chilly:"",
        white:"white.png",
        openSpots: 27,
    },
    {
        id: 3,
        title: "Red Curry Chicken",
        price: 7.99,
        coverImg: "redcurry.jpg",
        thumbUp: "thumbUp.png",
        chilly:"chiliLogo.jpg",
        white:"white.png",
        openSpots: 3,
    },
    {
        id: 4,
        title: "Green Curry Chicken",
        price: 7.99,
        coverImg: "greenCurry.jpg",
        thumbUp: "",
        chilly:"",
        white:"white.png",
        openSpots: 3,
    },
    {
        id: 5,
        title: "Santa Barbara Chicken",
        price: 7.99,
        coverImg: "santa.jpeg",
        thumbUp: "",
        chilly:"",
        white:"white.png",
        openSpots: 3,
    },
    {
        id: 6,
        title: "Bangkok Chicken",
        price: 7.99,
        coverImg: "bangkok.jpg",
        thumbUp: "",
        chilly:"chiliLogo.jpg",
        white:"white.png",
        openSpots: 3,
    },
    {
        id: 7,
        title: "Thai Chill Fish",
        price: 7.99,
        coverImg: "fish.jpeg",
        thumbUp: "",
        chilly:"chiliLogo.jpg",
        white:"white.png",
        openSpots: 3,
    }
]